- src: https://github.com/idi-ops/ansible-facts
- src: https://github.com/idi-ops/ansible-nodejs
- src: https://github.com/idi-ops/ansible-couchdb.git
- src: https://github.com/waharnum/ansible-gpii-preferences-server
