- src: https://github.com/idi-ops/ansible-facts
# - src: https://github.com/idi-ops/ansible-nodejs
- src: https://github.com/waharnum/ansible-nodejs-1
- src: https://github.com/waharnum/ansible-gpii-preferences-server
